### PR TITLE
Remove 'Trying to get property of non-object'

### PR DESCRIPTION
**Pull request by HZ-labs**

### CODE REVIEW

**Comment by zackkitzmiller** [comment]
Can you give some context as to why this would happen?

**Comment by HZ-labs** [comment]
Sometimes it caused by the low timeout. Getting NULL is better for us than showing error 500.

**Comment by zackkitzmiller** [comment]
It might be better to throw an exception in that? Then the caller can catch it.

**Comment by HZ-labs** [comment]
@zackkitzmiller we did it, but it doesn't work

**Pull request closed without merging**
